# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.16.4
minimal_mistakes_skin: "dark"
title   : Yet Another Blog
title_separator: "|"
name: Yet Another Blog
description: > # this means to ignore newlines until "Language & timezone"
  No Description yet
url     : https://micfan.github.io # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : / # does not include hostname
repository: micfan/micfan.github.io
repository_tree: master
head_scripts: []
breadcrumbs: true
search: true
# search_full_content: true
permalink: /blog/:categories/:title/
paginate: 8
paginate_path: /page:num # don't change this unless for special need

category_archive:
  type: liquid
  path: /cat/
tag_archive:
  type: liquid
  path: /tag/


## Development
host: 0.0.0.0

## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Sources
##############################
sources: unpkg # bootcdn (default), unpkg


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################

include:
  - _pages

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

markdown_ext: "markdown,mkdown,mkdn,mkd,md,MD"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: mysingle
      toc: true
      toc_label: "Contents"
      toc_icon: "bookmark"  # corresponding Font Awesome icon name (without fa prefix)
  # _posts
  - scope:
      path: "_posts/leetcode"
      type: posts
    values:
      layout: leetcode
      categories: leetcode
      toc: true
      toc_label: "Contents"
      toc_icon: "bookmark"  # corresponding Font Awesome icon name (without fa prefix)
  # _posts
  - scope:
      path: "_posts/book"
      type: posts
    values:
      layout: book
      categories: book
      toc: true
      toc_label: "Contents"
      toc_icon: "bookmark"  # corresponding Font Awesome icon name (without fa prefix)      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache


##
kramdown:
  syntax_highlighter: rouge


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false      
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true